

export const SIGNUP_SUCCES = 'SIGNUP_SUCCES';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';

export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_LOADING = 'LOGIN_LOADING';

export const LOGOUT_SUCCES = 'LOGOUT_SUCCES';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';

export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const FOLLOW_SEND_REQ_SUCCESS = 'FOLLOW_SEND_REQ_SUCCESS';
export const FOLLOW_SEND_REQ_LOADING = 'FOLLOW_SEND_REQ_LOADING';
export const FOLLOW_SEND_REQ_FAILED = 'FOLLOW_SEND_REQ_FAILED';

export const GET_SENT_REQ_SUCCESS = 'GET_SENT_REQ_SUCCESS';
export const GET_SENT_REQ_FAILED = 'GET_SENT_REQ_FAILED ';
export const GET_SENT_REQ_LOADING = 'GET_SENT_REQ_LOADING';
export const ADD_SENT_REQ = 'ADD_SENT_REQ';

export const CLEAR_USER_STATS = 'CLEAR_USER_STATS';

